### PR TITLE
 Do not define ENUM_BITFIELDS_NOT_SUPPORTED for MSVC

### PR DESCRIPTION
**Pull request by NickGerleman**
#### Please select one of the following
- [x] I am removing an existing difference between facebook/react-native and microsoft/react-native :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native :thumbsup:
- [ ] I am making a fix / change for the macOS implementation of react-native
- [x] I am making a change required for Microsoft usage of react-native

In order to move to OSS React Native, Windows needs to define
ENUM_BITFIELDS_NOT_SUPPORTED. This causes warnings treated as errors on
the microsoft fork due to macro redefinition. Remove the code that
automatically adds this definition.

This allows the removal of the YGStyle patch added to RNW.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native/pull/230)

### CODE REVIEW

**Comment by acoates-ms** [comment]
@tom-un is looking at getting a fix for the xcode issue.  (The image got updated and nolonger has the version of xcode we were using before).

**Comment by acoates-ms** [comment]
https://github.com/microsoft/react-native/pull/231 should fix the PR build

**Comment by kmelmon** [comment]
Thanks for moving this over!

**Comment by NickGerleman** [comment]
@kmelmon FYI,  @acoates-ms pointed we might not be able to remove this from RNW until later. We can talk more offline if interested, but it's very possible we can remove this with the 0.61 upgrade.

**Pull request merged**
