### PR TITLE
Added RN60 values for accessibilityRole and accessibilityStates

### PR DESCRIPTION
**Pull request by jonthysell**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native :thumbsup:
- [ ] I am making a fix / change for the macOS implementation of react-native
- [x] I am making a change required for Microsoft usage of react-native

#### Description of changes

Added the remaining RN60 accessibilityRole and accessibilityStates property values.

RNW uses these values here: https://github.com/microsoft/react-native-windows/commit/74cff3e1dc239ed02d2f3b2bf116f61993c7980e

This change just adds the values so that TS doesn't complain as we start using these values.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by ahimberg** [comment]
to clarify, TS will still complain until someone updates the @types (I'll probably try to do that just to see what the maintainers say, there are lots of props we'd like to add to the definitive types).  

this does fix yellowboxes that show even if you bypass TS checking.

**Comment by jonthysell** [comment]
> to clarify, TS will still complain until someone updates the @types (I'll probably try to do that just to see what the maintainers say, there are lots of props we'd like to add to the definitive types).
> 
> this does fix yellowboxes that show even if you bypass TS checking.

What else needs to be updated? My changes were a little 'shot in the dark', just searching for the property names, and comparing with FB 60-stable and master. Note, they've done a lot more refactoring in this area so I took the 'easy' route and just added the new values, without taking all of their changes.

**Comment by ahimberg** [comment]
This will unblock using the properties to not generate runtime warnings.  To get typescript fully happy these typing files -- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts -- which are written by hand and maintained by the community will also need updating.  Those are not microsoft forked, but given these new props are in RN60 they should be fine to contribute.  

we have some overrides in our project that also enable to extend @types/react-native, I haven't successfully extended these ones yet - still playing with it.

**Pull request merged**
